#ifndef EXCEPTION_TYPE_H
#define EXCEPTION_TYPE_H
typedef enum
{
    EXCEPTION_EXTERNAL_INTERRUPT,
    EXCEPTION_MACHINE_CHECK,
    EXCEPTION_DATA_STORAGE,
    EXCEPTION_PROGRAM_ERROR,
} ExceptionType;
#endif
